---
title: "Final Team Project" 
author: "Abizer, Matthew, Ping, Rosy"
date: "12/15/2022"
output: 
  github_document:
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, prompt=TRUE,comment=NULL,message=FALSE, echo = FALSE, include=TRUE, fig.width = 9, fig.height = 4) #This code chunk ensures that there are no commands in output file.
```

```{r packageCheck, include=FALSE}
mypacks <- c("ggplot2","dplyr","readr","tidyr", "ROCR", "boot","class","randomForest","e1071", "stringr","partykit","rpart","plyr","pracma","leaflet", "maps", "rgdal", "rgeos","leaflet", "tree","doParallel","foreach")  # what packages are needed?
packs <- installed.packages()   # find installed package list
install.me <- mypacks[!(mypacks %in% packs[,"Package"])]  #what needs to be installed?
if (length(install.me) >= 1) install.packages(install.me, repos = "http://cran.us.r-project.org")   # install (if needed)
lapply(mypacks, library, character.only=TRUE)  # load all packages
```

```{r}
uber_fare <- read_csv("C:/Users/munee/Desktop/econ122/finalproject-mpra/uber.csv")
```

```{r}
Q1_f <- quantile(uber_fare$fare_amount, .33)
Q2_f <- quantile(uber_fare$fare_amount, .66)
```

```{r}
uber_fare_mod <- uber_fare %>% mutate(pickup_time = str_extract(pickup_datetime,"[\\d]{1,2}:[\\d]{2}"), pickup_year = str_extract(pickup_datetime,"[\\d]{4}"), pickup_month_dash = str_extract(pickup_datetime, "-{1}[\\d]{2}-{1}"), pickup_month = str_extract(pickup_month_dash, "[\\d]{2}"), pickup_date_dash = str_extract(pickup_datetime, "-[\\d]{2}"), pickup_date = str_extract(pickup_date_dash, "[\\d]{2}"), pickup_longitude_mod = ifelse(pickup_longitude < -79.4554 | pickup_longitude > -71.4725, NA, pickup_longitude), pickup_latitude_mod = ifelse(pickup_latitude < 40.29400 | pickup_latitude > 45.00420, NA, pickup_latitude), dropoff_longitude_mod = ifelse(dropoff_longitude < -79.4554 | dropoff_longitude > -71.4725, NA, dropoff_longitude), dropoff_latitude_mod = ifelse(dropoff_latitude < 40.29400 | dropoff_latitude > 45.00420, NA, dropoff_latitude), time_range = ifelse(pickup_time < 12:00, "Morning", "Afternoon"), time_category = ifelse(pickup_time > 18:00, "Night", time_range ) ) %>% na.omit()


```

```{r}
uber_fare_mod <- filter_if(uber_fare_mod, is.numeric, all_vars((.) != 0)) %>% select(fare_amount, passenger_count, pickup_time, pickup_year, pickup_month, pickup_date, pickup_longitude_mod, pickup_latitude_mod, dropoff_longitude_mod, dropoff_latitude_mod, time_category)

```

```{r}
library(pracma)

dist_conversion <- function(lat1,lat2,lon1,lon2){
    lon1 = deg2rad(lon1)
    lon2 = deg2rad(lon2)
    lat1 = deg2rad(lat1)
    lat2 = deg2rad(lat2)
      
    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
 
    c = 2 * asin(sqrt(a))
    
    # Radius of earth in kilometers. Use 3956 for miles
    r = 3956
      
    # calculate the result
    return(c * r)
}

```

```{r}
uber_dist <- uber_fare_mod %>% mutate(distance = dist_conversion(pickup_latitude_mod,dropoff_latitude_mod, pickup_longitude_mod, dropoff_longitude_mod)) %>% filter(distance > 0, fare_amount>7.19)

```

```{r}
set.seed(7)
km_out <- kmeans(uber_dist[,7:10], centers = 4, nstart = 20)
uber_dist <- uber_dist %>% mutate(cluster_assign = as.character(km_out$cluster))
```

```{r eval = "FALSE"}
k<- 1:10

set.seed(11)

total.Wss <- sapply(k, function(x) kmeans(uber_dist[,7:10], centers=x, nstart=20)$tot.withinss)

ggplot(data_frame(total.Wss, k), aes(x=k,y=total.Wss)) + geom_point() + geom_line() + scale_x_continuous(breaks=1:10)
```

```{r}
uber_dist %>% group_by(cluster_assign) %>% dplyr::summarize(n = n()) 
```


```{r}
states <- map_data("state")
NY <- subset(states, region %in% c("new york", "new jersey"))

NY_county <- subset(map_data("county"), region == c("new york", "new jersey"))

ggplot(data = NY) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "gray", color = "white") + 
  coord_fixed(1.3) + geom_polygon(aes(x=long, y = lat), data = NY_county, fill = NA, color = "white") +
  geom_polygon(aes(x=long, y = lat),color = "black", fill = NA) + geom_point(data = uber_dist, aes(x = pickup_longitude_mod, y = pickup_latitude_mod, color = cluster_assign)) 
```

```{r}

uber_dist %>% select(distance, fare_amount) %>% gather(key = variable, value = value, distance:fare_amount) %>% ggplot(aes(x = variable, y = value)) + geom_boxplot() + facet_wrap(~variable, scales="free")+ ggtitle("Boxplots of Distance & Fare_amount")

#filter out distance outliers
Q1 <- quantile(uber_dist$distance, .25)
Q3 <- quantile(uber_dist$distance, .75)
IQR <- IQR(uber_dist$distance)


uber_dist_cleaner <- uber_dist %>% filter(distance < 6.306145 & distance > -1.57)

#filter out fare_amount outliers
Q1_f <- quantile(uber_dist$fare_amount, .25)
Q3_f <- quantile(uber_dist$fare_amount, .75)
IQR_f <- IQR(uber_dist$fare_amount)

uber_dist_cleaner <- uber_dist_cleaner %>% filter(fare_amount > -1.9 & fare_amount < 26.9)


```

```{r}
#decision tree
library(tree)
# Fitting a tree to lat and long
fitted_tree <- tree(fare_amount~pickup_latitude_mod+pickup_longitude_mod+ dropoff_latitude_mod+ dropoff_longitude_mod+ distance + passenger_count+pickup_month+pickup_date+pickup_time, uber_dist_clean)

# Draw a diagram of the tree structure
plot(fitted_tree)
text(fitted_tree)
summary(fitted_tree)
```


```{r}
set.seed(7)
n <- nrow(uber_dist_cleaner)
train_index <- sample(1:n, size=round(.1*n))

train <- uber_dist_cleaner %>% slice(train_index) %>% select(fare_amount, passenger_count, pickup_time, pickup_year, pickup_month, pickup_date, pickup_longitude_mod, pickup_latitude_mod, dropoff_longitude_mod, dropoff_latitude_mod, time_category, distance)

test <- uber_dist_cleaner %>% slice(-train_index) %>% select(fare_amount, passenger_count, pickup_time, pickup_year, pickup_month, pickup_date, pickup_longitude_mod, pickup_latitude_mod, dropoff_longitude_mod, dropoff_latitude_mod, time_category, distance)
```

```{r eval = FALSE}
ptm <- proc.time()

rf <- randomForest(fare_amount ~ pickup_latitude_mod+pickup_longitude_mod+ dropoff_latitude_mod+ dropoff_longitude_mod+ passenger_count+pickup_month+pickup_date+pickup_time+distance, data=train, ntree = 200)

rf

```


```{r}
importance(rf) 
```

```{r}
train <- train %>% mutate(prediction = predict(rf, type = "response"))

train %>% summarize(accuracy = mean(prediction == fare_amount))
```