---
title: "Final Team Project" 
author: "Abizer, Matthew, Ping, Rosy"
date: "12/15/2022"
output: 
  github_document:
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, prompt=TRUE,comment=NULL,message=FALSE, echo = FALSE, include=TRUE, fig.width = 9, fig.height = 4) #This code chunk ensures that there are no commands in output file.
```

```{r packageCheck, include=FALSE}
mypacks <- c("ggplot2","dplyr","readr","tidyr", "ROCR", "boot","class","randomForest","e1071", "stringr","partykit","rpart","plyr","pracma","leaflet", "maps", "rgdal", "rgeos", "leaflet")  # what packages are needed?
packs <- installed.packages()   # find installed package list
install.me <- mypacks[!(mypacks %in% packs[,"Package"])]  #what needs to be installed?
if (length(install.me) >= 1) install.packages(install.me, repos = "http://cran.us.r-project.org")   # install (if needed)
lapply(mypacks, library, character.only=TRUE)  # load all packages
```

```{r}
uber_fare <- uber
```

```{r}
uber_fare_mod <- uber_fare %>% mutate(pickup_time = str_extract(pickup_datetime,"[\\d]{1,2}:[\\d]{2}"), pickup_year = str_extract(pickup_datetime,"[\\d]{4}"), pickup_month_dash = str_extract(pickup_datetime, "-{1}[\\d]{2}-{1}"), pickup_month = str_extract(pickup_month_dash, "[\\d]{2}"), pickup_date_dash = str_extract(pickup_datetime, "-[\\d]{2}"), pickup_date = str_extract(pickup_date_dash, "[\\d]{2}"), pickup_longitude_mod = ifelse(pickup_longitude < -79.4554 | pickup_longitude > -71.4725, NA, pickup_longitude), pickup_latitude_mod = ifelse(pickup_latitude < 40.29400 | pickup_latitude > 45.00420, NA, pickup_latitude), dropoff_longitude_mod = ifelse(dropoff_longitude < -79.4554 | dropoff_longitude > -71.4725, NA, dropoff_longitude), dropoff_latitude_mod = ifelse(dropoff_latitude < 40.29400 | dropoff_latitude > 45.00420, NA, dropoff_latitude) ) %>% na.omit()

glimpse(uber_fare_mod)
summary(uber_fare_mod)
```

```{r}
uber_fare_mod <- filter_if(uber_fare_mod, is.numeric, all_vars((.) != 0)) %>% select(fare_amount, passenger_count, pickup_time, pickup_year, pickup_month, pickup_date, pickup_longitude_mod, pickup_latitude_mod, dropoff_longitude_mod, dropoff_latitude_mod)

```

```{r}
uber_fare_mod %>% select(fare_amount, passenger_count, pickup_time, pickup_year, pickup_month, pickup_date, pickup_latitude_mod, pickup_longitude_mod, dropoff_latitude_mod, dropoff_longitude_mod) %>% filter(pickup_year=="2015")
```

```{r}
library(pracma)

dist_conversion <- function(lat1,lat2,lon1,lon2){
    lon1 = deg2rad(lon1)
    lon2 = deg2rad(lon2)
    lat1 = deg2rad(lat1)
    lat2 = deg2rad(lat2)
      
    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
 
    c = 2 * asin(sqrt(a))
    
    # Radius of earth in kilometers. Use 3956 for miles
    r = 3956
      
    # calculate the result
    return(c * r)
}

```

```{r}
uber_dist <- uber_fare_mod %>% mutate(distance = dist_conversion(pickup_latitude_mod,dropoff_latitude_mod, pickup_longitude_mod, dropoff_longitude_mod)) %>% filter(distance > 0, fare_amount>7.19) %>% filter(pickup_year=="2015")

glimpse(uber_dist)
```

```{r}
km_out <- kmeans(uber_dist[,7:10], centers = 3, nstart = 20)
uber_dist <- uber_dist %>% mutate(cluster_assign = as.character(km_out$cluster))
```

```{r}
uber_dist %>% ggplot(aes(x = scale(pickup_latitude_mod), y = scale(pickup_longitude_mod))) + geom_point(aes(color = cluster_assign)) 
```

```{r}
uber_dist %>% group_by(cluster_assign) %>% dplyr::summarize(n = n()) 
```


```{r}

states <- map_data("state")
NY <- subset(states, region %in% c("new york", "new jersey"))

NY_county <- subset(map_data("county"), region == c("new york", "new jersey"))

ggplot(data = NY) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "gray", color = "white") + 
  coord_fixed(1.3) + geom_polygon(aes(x=long, y = lat), data = NY_county, fill = NA, color = "white") +
  geom_polygon(aes(x=long, y = lat),color = "black", fill = NA) + geom_point(data = uber_dist, aes(x = pickup_longitude_mod, y = pickup_latitude_mod, color = cluster_assign)) 


```

```{r}
uber_dist_mod2 <- uber_dist %>% filter(cluster_assign == "2") %>% select(dropoff_latitude_mod, dropoff_longitude_mod)


```


#Cluster 2 Pickup= Manhattan Area with some points in Brooklyn (very similar to cluster 1 but has less points somehow??)
#Cluster 2 Dropoff is more upper manhattan with end points in JFK and La Guardia and some in Brooklyn with some outliers in the Bronx
```{r}
library(leaflet)
uber_dist_mod2 <- sample_frac(uber_dist_mod2, 0.1)



map <- leaflet(data=uber_dist_mod2) %>% addTiles() %>% addMarkers(~dropoff_longitude_mod, ~dropoff_latitude_mod)

map
```


```{r}
#Cluster 1 pickup = Manhattan Area with some points in Brooklyn
#Cluster 1 dropoff is manhattan Area with more points in Brooklyn and 1 point in Newwark
uber_dist_mod1 <- uber_dist %>% filter(cluster_assign == "1") %>% select(dropoff_latitude_mod, dropoff_longitude_mod)

uber_dist_mod1 <- sample_frac(uber_dist_mod1, 0.005)



map <- leaflet(data=uber_dist_mod1) %>% addTiles() %>% addMarkers(~dropoff_longitude_mod, ~dropoff_latitude_mod)

map
```

```{r}
#cluster 3 Pickup= JFK airport and LaGuardia
#Cluster 3 Dropoff = Manhattan with some points in JFk and LaGuardia                                                                                                                                                                                      

uber_dist_mod3 <- uber_dist %>% filter(cluster_assign == "3") %>% select(dropoff_latitude_mod, dropoff_longitude_mod)

uber_dist_mod3 <- sample_frac(uber_dist_mod3, 0.005)



map <- leaflet(data=uber_dist_mod3) %>% addTiles() %>% addMarkers(~dropoff_longitude_mod, ~dropoff_latitude_mod)

map

```

```{r}


uber_dist_clean %>% ggplot(aes(x=distance, y=fare_amount)) + geom_point()



```
```{r}

```

```{r}
#filter out distance outliers
Q1 <- quantile(uber_dist$distance, .0001)
Q3 <- quantile(uber_dist$distance, .9999)
IQR <- IQR(uber_dist$distance)


uber_dist_clean <- subset(uber_dist, uber_dist$distance > (Q1 - 1.5*IQR) & uber_dist$distance < (Q3 + 1.5*IQR))

#filter out fare_amount outliers
#Q1_f <- quantile(uber_dist$fare_amount, .01)
#Q3_f <- quantile(uber_dist$fare_amount, .99)
#IQR_f <- IQR(uber_dist$fare_amount)

#uber_dist_clean <- subset(uber_dist, uber_dist$fare_amount > (Q1 - 1.5*IQR) & uber_dist$fare_amount < (Q3 + 1.5*IQR))

uber_dist_clean <- uber_dist_clean %>% filter(fare_amount<130)
```

```{r}





```